### ISSUE TITLE
Getting a error after install

### ISSUE THREAD

**Issue by lauwiex** [flagbit/akeneo-product-cloner#15]
Hi,

The product edit page in Akeneo has stopped working.

Any idea about this. I did al the steps

Steps I have take
- adding to Appkernel.php and routing.yml the needed lines.
- Flushed cache
- Reindex

[Error] flagbit/product-edit-form/clone is missing from the registry - include it in your requirejs.yml and clear the app cache
	
[Error] Error: 
The module "flagbit/product-edit-form/clone" is undefined.
Most of the time it's because it's not well registered in your requirejs.yml file.
Here is the documentation to fix this problem
https://docs.akeneo.com/latest/design_pim/overview.html#register-it

**Comment by amansilla** [comment]
Hi @lauwiex, did you try regenerating the assets with the following command? Maybe it's an issue with the browser cache?

```
php bin/console pim:installer:assets --symlink --clean --env=prod
yarn run webpack
```

**Comment by amansilla** [comment]
Hi @lauwiex, did you get your issue with the installation solved?

**Comment by amansilla** [comment]
This issue will be closed because of lack of feedback.

Please feel free to reopen it if the issue still persists.

**Comment by lauwiex** [comment]
Hi @amansilla ,

Sorry for the late respond. It is working right now.. It was indeed a (local and cloudflare) cache problem. 

Thanks!

**Comment by amansilla** [comment]
@lauwiex that's great! 

I'm happy you got your issue solved. Cheers!🥂
