### ISSUE TITLE
Cloning product model fails in 3.2

### ISSUE THREAD

**Issue by excursions** [flagbit/akeneo-product-cloner#21]
The family code has been added in the product model format [in 3.2](https://github.com/akeneo/pim-community-dev/blob/3.2/CHANGELOG-3.2.md#features-1) ( TIP-1144 ) which makes it impossible to update the Cloned Product Model ( since the ProductModelUpdater [does not expect it](https://github.com/akeneo/pim-community-dev/blob/3.2/src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php#L131) )

**Comment by flagbird** [comment]
Fixed with #25.
