### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by wespiremedia** [Flagbit/akeneo-product-cloner#3]
I've installed your extension successfully, but have no idea how to use it. Don't see any button or anything. 

Can you please tell me how to use it or send a screenshot?

**Comment by henrique-redstage** [comment]
oh.. I thought I was the only one.. I don't see any button too

**Comment by amansilla** [comment]
Hi @wespiremedia and @henrique-redstage! First thank you for using the bundle and providing us this important feedback.

We've updated the readme file with some screen captures (see #4), so I'll close this issue.

Just in case you still are missing some details, please reopen the issue or add a new one.

**Comment by wespiremedia** [comment]
The documentation is clear to me right now, but unfortunately the 'Clone' button doesn't appear in the dropdown menu. 

I've completed all steps successfully and see no errors in the console.

**Comment by amansilla** [comment]
Please check you're trying to clone a abstract product, since actually the bundle only provide the clone functionality for abstract products and not for simple or variants.

**Comment by wespiremedia** [comment]
I try to edit a product, I don't know the difference between abstract and simple products? Akeneo documentation doesn't tell anything about different kind of products.

**Comment by amansilla** [comment]
Take a look to the [official Akeneo documentation](https://help.akeneo.com/articles/what-about-products-variants.html).

**Comment by wespiremedia** [comment]
I'm trying to clone a product, not a variation.

**Comment by amansilla** [comment]
Ok, right know only product models are clonable, so cloning normal products is still not implemented in this first version of the module.
